### ISSUE TITLE
bob not picking up 1.18.1 ?

### ISSUE THREAD

**Issue by ltd** [hexpm/bob#201]
Bob doesn't seem to be picking up 1.18.1.

**Comment by rhcarvalho** [comment]
Not sure if related, but it also didn't pick up a newer Ubuntu base image pushed 23 days ago:

https://hub.docker.com/_/ubuntu/tags?name=noble

> [noble-20241118.1](https://hub.docker.com/layers/library/ubuntu/noble-20241118.1/images/sha256-6e75a10070b0fcb0bead763c5118a369bc7cc30dfc1b0749c491bbb21f15c3c7)
> 
> Last pushed 23 days ago

The latest images are based on `noble-20241015`.

**Comment by chulkilee** [comment]
https://builds.hex.pm/builds/elixir/builds.txt has 1.18.1 (built on 12/24) but no new docker images are pushed to https://hub.docker.com/r/hexpm/elixir

**Comment by ericmj** [comment]
The images are in the build queue now.

**Comment by rhcarvalho** [comment]
> The images are in the build queue now.

Thanks @ericmj! Are the Ubuntu versions supposed to update automatically too?

https://hub.docker.com/r/hexpm/elixir/tags?name=1.18.1-erlang-27.2-ubuntu-noble

Lists `1.18.1-erlang-27.2-ubuntu-noble-20241015`, but the latest `noble` image is `noble-20241118.1` (hmmm maybe a regexp is missing the image because of the trailing `.1`? I'll have a look...)

Oh that's it: https://github.com/hexpm/bob/blob/d5ce4399b7761a5f9487eb056d30a1d6bed459bf/lib/bob/job/docker_checker.ex#L19C21-L19C24

I'll send a PR.
