### ISSUE TITLE
Create docs_config.js for Elixir, ExDoc, Hex etc

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/bob#30]
Ref: https://github.com/hexpm/hexdocs/pull/9

**Comment by michallepicki** [comment]
Is this issue about adding the `master` version link to the dropdown?

Is it also about fixing the links to Elixir v1.0.0 - v1.0.3 or is it a separate issue?

**Comment by ericmj** [comment]
I think we should add `master` to the dropdown based on other discussions. Do you agree @josevalim?

We don't have docs builds for Elixir v1.0.0 - v1.0.3 so we should remove those links from the dropdown.

**Comment by wojtekmach** [comment]
I actually initially had master in the dropdown (5d2fc6b) but then on https://hexdocs.pm/elixir/master/Kernel.html page the dropdown had both "1.9.0-dev" _and_ master which was confusing. When building config I could see that the latest tag is v1.8.1 so the next dev version _should_ be v1.9.0 and put that into the list with the link to master, but I'm afraid this could be too clever and error prone.

I've removed links for 1.0.0..1.0.3, good catch!

**Comment by josevalim** [comment]
> When building config I could see that the latest tag is v1.8.1 so the next dev version should be v1.9.0-dev and put that into the list with the link to master, but I'm afraid this could be too clever and error prone.

This will be fine for a long long long time, at least until we start work on v2.0, so I am ok with it.

**Comment by wojtekmach** [comment]
@josevalim just so we're clear, you're saying to add 1.9.0-dev (or whatever the latest dev version is) to the config.js or leave things as is?

**Comment by michallepicki** [comment]
@wojtekmach I see. You can take a look at my code [here](https://github.com/elixir-lang/ex_doc/pull/970/files#diff-fdbed5284a2334ea2f3dab02fb0269d6R19) - for people maintaining their own versions, for convenience and so that things don't break, we're prepending the list with an entry for the current version if it's seemingly missing. The current version name is being read from what was displayed instead of the version dropdown, so indeed for the current master it's v1.9.0-dev.

Looks like having an option v1.9.0-dev is the easy way to go for now, I actually don't mind if it would be called that. We could change my code in ExDoc if we want to display `master` there

**Comment by josevalim** [comment]
> leave things as is?

This. :)
