### ISSUE TITLE
Docker: Some 1.10.4/23.0.4 ARM64 builds are missing

### ISSUE THREAD

**Issue by nifoc** [hexpm/bob#56]
It looks like the following images have no ARM64 version on Docker Hub:

* `1.10.4-erlang-23.0.4-debian-jessie-20200607`
* `1.10.4-erlang-23.0.4-ubuntu-focal-20200703`
* `1.10.4-erlang-23.0.4-ubuntu-bionic-20200630`

**Comment by ericmj** [comment]
Do you mean AMD64? Docker had cached corrupted downloads that were continually failing to untar. It's fixed now and the images should be coming up as soon as they are built.

The ARM64 images have been up since since the release of 23.0.4. We don't have ARM64 images for debian jessie because we cannot build them on that debian version.

**Comment by nifoc** [comment]
> Do you mean AMD64? Docker had cached corrupted downloads that were continually failing to untar. It's fixed now and the images should be coming up as soon as they are built.

You're of course correct. It was AMD64 and not ARM64 -- I misread some CI logs.  
Everything is okay now.

Sorry for the confusion.
