### ISSUE TITLE
Changing Docker Tags

### ISSUE THREAD

**Issue by maennchen** [hexpm/bob#75]
It would be great if the images could be tagged using multiple tags. For example:

* `hexpm/elixir:1.10.2-erlang-22.2.8-alpine-3.11.3`
* `hexpm/elixir:1.10.2-erlang-22.2-alpine`
* `hexpm/elixir:1.10.2-erlang-22-alpine`
* `hexpm/elixir:1.10.2-alpine`
* `hexpm/elixir:1.10-alpine`
* etc.

This would allow to get automatic security updates / bugfixes.

An example how that could work can be found in the PR: https://github.com/c0b/docker-elixir/pull/127/files#diff-54a405a70b571bc6fec28b63fc91cdd1e7a47d3edae70251442be7bd4bf15ce5R1

**Comment by ericmj** [comment]
We are not planning to do this because it goes against the reasons why we created these images [1]. It would create very many tags for all different combinations and some of the software we build on images on such as erlang and linux distributions do not follow semver so removing parts of the version string is ambiguous. If you want automatically changing images we recommend the official images or you should update images based on other automation such as CI.

[1] https://elixirforum.com/t/yet-another-elixir-and-erlang-docker-image/28740
